apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - deployment.yml
  - svc.yml

configMapGenerator:
  - name: hello-kubernetes
    literals:
    - MESSAGE=Hello, Kubernetes!

