
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  labels:
    app.kubernetes.io/name: hello-kubernetes
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-kubernetes
