apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-hello

resources:
  - ../base

configMapGenerator:
  - name: hello-kubernetes
    behavior: merge
    literals:
    - MESSAGE=Hello, Production!

